services:
  codeg-user1:
    image: ghcr.io/tose123/codeg:latest
    container_name: codeg-user1
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    environment:
      - CODEG_TOKEN=${CODEG_TOKEN:-}
      - CODEG_PORT=3080
      - CODEG_UPLOAD_MAX_TOTAL_BYTES=2147483648 # 2GiB
    ports:
      - 3080:3080
    volumes:
      - ./data/user1:/root
    restart: unless-stopped
